// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORM_LINQ.Models.DB;

#nullable disable

namespace ORM_LINQ.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AddressCustomer", b =>
                {
                    b.Property<int>("AddressesMyAddressId")
                        .HasColumnType("int");

                    b.Property<int>("CustomersCustomerId")
                        .HasColumnType("int");

                    b.HasKey("AddressesMyAddressId", "CustomersCustomerId");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("AddressCustomer");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Address", b =>
                {
                    b.Property<int>("MyAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("city");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("postal_code");

                    b.HasKey("MyAddressId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("ORM_LINQ.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BillId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Bill_Article", b =>
                {
                    b.Property<int>("Bill_ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("ActPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.HasKey("Bill_ArticleId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("BillId");

                    b.ToTable("Bill_Articles");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsMale")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Evaluation", b =>
                {
                    b.Property<int>("MyEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evaluation_id");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasColumnName("stars");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("evaluation_text");

                    b.HasKey("MyEvaluationId");

                    b.HasIndex("ArticleId");

                    b.ToTable("evaluations");
                });

            modelBuilder.Entity("AddressCustomer", b =>
                {
                    b.HasOne("ORM_LINQ.Models.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressesMyAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORM_LINQ.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ORM_LINQ.Models.Bill_Article", b =>
                {
                    b.HasOne("ORM_LINQ.Models.Article", "Article")
                        .WithMany("Bill_Articles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ORM_LINQ.Models.Bill", "Bill")
                        .WithMany("Bill_Articles")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Evaluation", b =>
                {
                    b.HasOne("ORM_LINQ.Models.Article", "Article")
                        .WithMany("Evaluations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Article", b =>
                {
                    b.Navigation("Bill_Articles");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("ORM_LINQ.Models.Bill", b =>
                {
                    b.Navigation("Bill_Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
